@startuml
skinparam defaultTextAlignment center
skinparam componentStyle uml2

skinparam queue {
    BorderColor Black
}
skinparam queue<<Events>> {
    BackgroundColor LightGreen
}
skinparam queue<<Commands>> {
    BackgroundColor LightBlue
}
skinparam queue<<Notify>> {
    BackgroundColor Pink
}
skinparam queue<<System>> {
    BackgroundColor LightYellow
}

title Broker Component & Data Flow (with Telegram)

package "RabbitMQ + MQTT plugin" {

    queue "1. События от датчиков" as events <<Events>>
    note bottom: Топик: home/events/+/state\n(Температура изменилась, движение обнаружено)

    queue "2. Команды устройствам" as commands <<Commands>>
    note bottom: Топик: home/commands/+/set\n(Включить, Изменить цвет)

    queue "3. Уведомления (Dispatch)" as notify <<Notify>>
    note bottom: Топик: sys/notify/dispatch\n(Payload: notificationData)

}

component "Connect Service" as connect
component "Core Service" as core
component "Automation Service" as auto
component "Notifier Service" as notifier

cloud "Telegram API" as tg_cloud
database "DB Notifier Schema" as db_notifier

connect -down-> events : Pub
events -up-> core : Sub
events -up-> auto : Sub

core -down-> commands : Pub
auto -down-> commands : Pub
commands -up-> connect : Sub

auto -down-> notify : Pub (Уведомления от автоматизаций и датчиков)
core -down-> notify : Pub (Системные уведомления)
notify -up-> notifier : Sub
notifier -right-> tg_cloud : HTTPS POST\n(Отправка)

tg_cloud -left-> notifier : Webhook\n(/start)
notifier -down-> db_notifier : Привязка аккаунта\n(сохраняет в свою БД)

core -right-> notifier : Internal API\n(управление каналами)
core -left-> connect : Internal API\n(каталог устройств, паспорта)

@enduml
